name: Auth
version: '1.0'
main: ah.s4lpicon.auth.Auth
api-version: '1.21'
author: S4LPICON
description: Holis
commands:
  logueo:
    description: Muestra un mensaje al jugador.
    usage: /<command>
  debuginfo:
    description: Información de depuración.
    usage: /<command>